
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOREQ = 19;
  public static final int PORIGUAL = 42;
  public static final int AC = 7;
  public static final int CHAR = 52;
  public static final int POR = 11;
  public static final int UMINUS = 29;
  public static final int ENTERO = 60;
  public static final int CASE = 48;
  public static final int MONTE = 54;
  public static final int DECR = 33;
  public static final int INTERR = 44;
  public static final int INT = 30;
  public static final int INCR = 32;
  public static final int FOR = 27;
  public static final int ENTREIGUAL = 43;
  public static final int CP = 4;
  public static final int AND = 21;
  public static final int IGUAL = 17;
  public static final int STRINGTEXT = 63;
  public static final int MASIGUAL = 40;
  public static final int IN = 38;
  public static final int CFLOAT = 37;
  public static final int OR = 22;
  public static final int DIV = 12;
  public static final int CHARTEXT = 62;
  public static final int CC = 8;
  public static final int IF = 23;
  public static final int AMPERSAND = 51;
  public static final int DIST = 18;
  public static final int EOF = 0;
  public static final int ASIG = 13;
  public static final int error = 1;
  public static final int COMA = 31;
  public static final int MENOS = 10;
  public static final int MENOR = 16;
  public static final int MOD = 34;
  public static final int IDENT = 59;
  public static final int BREAK = 50;
  public static final int ERROR = 39;
  public static final int CLL = 6;
  public static final int SWITCH = 47;
  public static final int REAL = 61;
  public static final int ELVIS = 46;
  public static final int MAYOR = 15;
  public static final int MAYUS = 55;
  public static final int NEG = 14;
  public static final int CINT = 36;
  public static final int ELSE = 24;
  public static final int PUNTO = 56;
  public static final int CCHAR = 53;
  public static final int WHILE = 25;
  public static final int DEFAULT = 49;
  public static final int FLOAT = 35;
  public static final int MENOSIGUAL = 41;
  public static final int STRING = 58;
  public static final int ALL = 5;
  public static final int MAYOREQ = 20;
  public static final int AP = 3;
  public static final int DP = 45;
  public static final int LENGTH = 57;
  public static final int PRINT = 28;
  public static final int DO = 26;
  public static final int PYC = 2;
  public static final int MAS = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PYC",
  "AP",
  "CP",
  "ALL",
  "CLL",
  "AC",
  "CC",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "ASIG",
  "NEG",
  "MAYOR",
  "MENOR",
  "IGUAL",
  "DIST",
  "MENOREQ",
  "MAYOREQ",
  "AND",
  "OR",
  "IF",
  "ELSE",
  "WHILE",
  "DO",
  "FOR",
  "PRINT",
  "UMINUS",
  "INT",
  "COMA",
  "INCR",
  "DECR",
  "MOD",
  "FLOAT",
  "CINT",
  "CFLOAT",
  "IN",
  "ERROR",
  "MASIGUAL",
  "MENOSIGUAL",
  "PORIGUAL",
  "ENTREIGUAL",
  "INTERR",
  "DP",
  "ELVIS",
  "SWITCH",
  "CASE",
  "DEFAULT",
  "BREAK",
  "AMPERSAND",
  "CHAR",
  "CCHAR",
  "MONTE",
  "MAYUS",
  "PUNTO",
  "LENGTH",
  "STRING",
  "IDENT",
  "ENTERO",
  "REAL",
  "CHARTEXT",
  "STRINGTEXT"
  };
}

