
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Y = 8;
  public static final int AC = 19;
  public static final int CHAR = 39;
  public static final int POR = 6;
  public static final int ENTERO = 34;
  public static final int DIFERENTE = 12;
  public static final int O = 9;
  public static final int INT = 37;
  public static final int FOR = 32;
  public static final int CP = 18;
  public static final int IGUAL = 11;
  public static final int CC = 20;
  public static final int IF = 28;
  public static final int COMILLA_DOBLE = 42;
  public static final int EOF = 0;
  public static final int ASIG = 2;
  public static final int error = 1;
  public static final int COMA = 24;
  public static final int MENOS = 4;
  public static final int MENOR = 13;
  public static final int IDENT = 33;
  public static final int MENOSUNARIO = 5;
  public static final int CLL = 22;
  public static final int REAL = 35;
  public static final int MAYOR = 14;
  public static final int ELSE = 29;
  public static final int PUNTO = 23;
  public static final int WHILE = 31;
  public static final int COMILLA_SIMPLE = 41;
  public static final int MAYOR_IGUAL = 16;
  public static final int FLOAT = 38;
  public static final int STRING = 40;
  public static final int ALL = 21;
  public static final int MENOR_IGUAL = 15;
  public static final int ENTRE = 7;
  public static final int ASCII = 36;
  public static final int AP = 17;
  public static final int NEGADO = 10;
  public static final int PRINT = 26;
  public static final int LENGTH = 27;
  public static final int DO = 30;
  public static final int PYC = 25;
  public static final int MAS = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ASIG",
  "MAS",
  "MENOS",
  "MENOSUNARIO",
  "POR",
  "ENTRE",
  "Y",
  "O",
  "NEGADO",
  "IGUAL",
  "DIFERENTE",
  "MENOR",
  "MAYOR",
  "MENOR_IGUAL",
  "MAYOR_IGUAL",
  "AP",
  "CP",
  "AC",
  "CC",
  "ALL",
  "CLL",
  "PUNTO",
  "COMA",
  "PYC",
  "PRINT",
  "LENGTH",
  "IF",
  "ELSE",
  "DO",
  "WHILE",
  "FOR",
  "IDENT",
  "ENTERO",
  "REAL",
  "ASCII",
  "INT",
  "FLOAT",
  "CHAR",
  "STRING",
  "COMILLA_SIMPLE",
  "COMILLA_DOBLE"
  };
}

