
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 59;
  public static final int DIV_EQ = 21;
  public static final int O_PAR = 4;
  public static final int LTE = 29;
  public static final int MULT = 12;
  public static final int CHAR = 51;
  public static final int CAST_FLOAT = 54;
  public static final int MINUS_MINUS = 17;
  public static final int CASE = 41;
  public static final int CONTINUE = 47;
  public static final int INT = 49;
  public static final int FOR = 44;
  public static final int MINUS = 11;
  public static final int CAST_CHAR = 55;
  public static final int NOT = 32;
  public static final int SEMICOLON = 2;
  public static final int AND = 30;
  public static final int LT = 27;
  public static final int C_PAR = 5;
  public static final int MULT_EQ = 20;
  public static final int OR = 31;
  public static final int DIV = 13;
  public static final int FLOAT_CONST = 58;
  public static final int PLUS = 10;
  public static final int IF = 38;
  public static final int ASSIGN = 23;
  public static final int AMPERSAND = 33;
  public static final int ID = 56;
  public static final int CAST_INT = 53;
  public static final int DOT = 37;
  public static final int EOF = 0;
  public static final int RETURN = 48;
  public static final int PLUS_PLUS = 16;
  public static final int INT_CONST = 57;
  public static final int error = 1;
  public static final int COMA = 3;
  public static final int MOD = 14;
  public static final int NEQ = 25;
  public static final int C_BRACK = 9;
  public static final int BREAK = 46;
  public static final int EQ = 24;
  public static final int O_BRACK = 8;
  public static final int GTE = 28;
  public static final int SWITCH = 40;
  public static final int ELVIS = 36;
  public static final int C_CURL = 7;
  public static final int MOD_EQ = 22;
  public static final int COLON = 35;
  public static final int ELSE = 39;
  public static final int WHILE = 43;
  public static final int DEFAULT = 42;
  public static final int FLOAT = 50;
  public static final int STRING = 52;
  public static final int QUESTION = 34;
  public static final int PLUS_EQ = 18;
  public static final int MINUS_SIGN = 15;
  public static final int O_CURL = 6;
  public static final int MINUS_EQ = 19;
  public static final int STRING_CONST = 60;
  public static final int GT = 26;
  public static final int LENGTH = 62;
  public static final int PRINT = 61;
  public static final int DO = 45;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMICOLON",
  "COMA",
  "O_PAR",
  "C_PAR",
  "O_CURL",
  "C_CURL",
  "O_BRACK",
  "C_BRACK",
  "PLUS",
  "MINUS",
  "MULT",
  "DIV",
  "MOD",
  "MINUS_SIGN",
  "PLUS_PLUS",
  "MINUS_MINUS",
  "PLUS_EQ",
  "MINUS_EQ",
  "MULT_EQ",
  "DIV_EQ",
  "MOD_EQ",
  "ASSIGN",
  "EQ",
  "NEQ",
  "GT",
  "LT",
  "GTE",
  "LTE",
  "AND",
  "OR",
  "NOT",
  "AMPERSAND",
  "QUESTION",
  "COLON",
  "ELVIS",
  "DOT",
  "IF",
  "ELSE",
  "SWITCH",
  "CASE",
  "DEFAULT",
  "WHILE",
  "FOR",
  "DO",
  "BREAK",
  "CONTINUE",
  "RETURN",
  "INT",
  "FLOAT",
  "CHAR",
  "STRING",
  "CAST_INT",
  "CAST_FLOAT",
  "CAST_CHAR",
  "ID",
  "INT_CONST",
  "FLOAT_CONST",
  "CHAR_CONST",
  "STRING_CONST",
  "PRINT",
  "LENGTH"
  };
}

